version: '3.9'

services:
  example:
    image: andreaswachs/daaukins-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure:5
    expose:
      - 50052
    ports:
      - 50052:50051
    environment:
      - DAAUKINS_USING_DOCKER_COMPOSE=hell_yeah
      - DAAUKINS_SERVER_CONFIG=server.yaml
      - DAAUKINS_STORE_CONFIG=store.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./server.yaml:/app/server.yaml:ro
      - ./store.yaml:/app/store.yaml:ro
      - /tmp:/tmp
